name: llm_guided_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy
  - torchvision
  - cudatoolkit=11.3
  - transformers
  - uvicorn
  - fastapi
  - pip:
    - torch
    - accelerate
    - -r requirements.txt
    - numpy
    - tqdm
    - hydra-core==1.2
    - omegaconf